version: '3'

services:
  proxy:
    env_file:
      - .env
    build: 
      context: ./proxy/
    ports:
      - "2000:2000/udp"
    depends_on:
      - native
      - xml
      - json
      - avro
      - proto
      - msgpack
      - yaml

  _workbuilder:
    image: workernode
    build:
      context: ./worker/

  native:
    image: workernode
    environment:
      - METHOD=native
    depends_on:
      - _workbuilder
    env_file:
      - .env
    hostname: native
    command: python3 worker_node.py

  xml:
    image: workernode
    environment:
      - METHOD=xml
    depends_on:
      - _workbuilder
    env_file:
      - .env
    hostname: xml
    command: python3 worker_node.py

  json:
    image: workernode
    environment:
      - METHOD=json
    depends_on:
      - _workbuilder
    env_file:
      - .env
    hostname: json
    command: python3 worker_node.py

  avro:
    image: workernode
    environment:
      - METHOD=avro
    depends_on:
      - _workbuilder
    env_file:
      - .env
    hostname: avro
    command: python3 worker_node.py

  msgpack:
    image: workernode
    environment:
      - METHOD=msgpack
    depends_on:
      - _workbuilder
    env_file:
      - .env
    hostname: msgpack
    command: python3 worker_node.py

  proto:
    image: workernode
    environment:
      - METHOD=proto
    depends_on:
      - _workbuilder
    env_file:
      - .env
    hostname: proto
    command: python3 worker_node.py
  
  yaml:
    image: workernode
    environment:
      - METHOD=yaml
    depends_on:
      - _workbuilder
    env_file:
      - .env
    hostname: yaml
    command: python3 worker_node.py
